!#################################
MODULE MOD_VARIABLES
	USE MOD_PARAM
	IMPLICIT NONE
    INTEGER  			:: NX, NZ		    ! MODEL SIZE PARAMETERS
    INTEGER				:: NAB, TOPBC    		  !   0=> FS AT TOP,  1=> PML ALL SIDE
    REAL(KIND=DP)		:: MDX, MDZ, DH
    REAL(KIND=DP)		:: DT,F0,T0,T, NT    ! SOURCE SHAPE PARAMETERS 
    INTEGER				:: STYPE
	INTEGER				:: SS_INT=1,  WF_INT=9999999    ! NO OF STEPS TO SKIP 
END MODULE MOD_VARIABLES